### ISSUE TITLE
Failed to load model

### ISSUE THREAD

**Issue by Maruzeru** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#21]
I am trying to get this running but it never seems to work. Windows, Python 3.11.7, VS R65.
I have all the model folders with the PARAM and BIN files inside "models" folder inside Vapoursynth\plugins, where librife.dll is.
This path is added to environment variables. All loads correctly except the models. I have checked permissions and even with admin priviliges it doesn't work.
I have tried to set exact path to model with the "model_path=" parameter but it also gives the same error Failed to load model.
What am I doing wrong? In the past it was working for me perfectly with HomeOfVapoursynthEvolution version and your first versions as well.

**Comment by styler00dollar** [comment]
That sounds like user error to me since I did not change the code since I forked the repository. I am only updating ncnn submodules and add converted models. The conversion from PyTorch to ncnn is not very straight forward and the main maintenance work.

The easiest way to use this plugin is to just git clone the repo into desktop and place the compiled binary into this folder. Then load the plugin manually.
```
core.std.LoadPlugin(path="/path/librife.dll")
```
The `models` folder needs to be in the same folder as the `dll`/`so`/`dylib`.

**Comment by dexeonify** [comment]
> The `models` folder needs to be in the same folder as the `dll`/`so`/`dylib`.

As a new VapourSynth user who has never dealt with the HomeOfVapoursynthEvolution's version before, it would be kind of you to at least mention that somewhere in the README. Although less necessary, it would also be good to clarify the target OS for each `dll`/`so`/`dylib` file.

**Comment by styler00dollar** [comment]
> it would be kind of you to at least mention that somewhere in the README

The official readme never said it as well, but I guess it could be added for clarification.

> it would also be good to clarify the target OS for each dll/so/dylib file.

I kind of expect basic knowledge. It is like explaining that exe files belong to windows.

**Comment by styler00dollar** [comment]
Closing due to lack of updates, should be solved by placing the models folder correctly. I did add more verbose filenames in release builds at least.
