### ISSUE TITLE
🙏 [Feature Request] Support 8/12FPS anime interpolation

### ISSUE THREAD

**Issue by steelywing** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#28]
Normally anime use the same 1 frame for 2~3 frames (8/12 FPS) in 24FPS video, a demo video in 

https://github.com/hzwer/Practical-RIFE/pull/23

It is a bit like current `skip` function, but instead of copy the frame, interpolation use the next non-still frame

**Comment by styler00dollar** [comment]
I think what you want is called ddfi. You can use [Mr-Z-2697/ddfi-rife](https://github.com/Mr-Z-2697/ddfi-rife) and [styler00dollar/VSGAN-tensorrt-docker](https://github.com/styler00dollar/VSGAN-tensorrt-docker?tab=readme-ov-file#ddfi) for reference since both show usage with vapoursynth. This won't be included in the plugin and you can just adjust your vapoursynth script for that.

**Comment by steelywing** [comment]
> I think what you want is called ddfi. You can use [Mr-Z-2697/ddfi-rife](https://github.com/Mr-Z-2697/ddfi-rife) and [styler00dollar/VSGAN-tensorrt-docker](https://github.com/styler00dollar/VSGAN-tensorrt-docker?tab=readme-ov-file#ddfi) for reference since both show usage with vapoursynth. This won't be included in the plugin and you can just adjust your vapoursynth script for that.

Yes, I want to do this. Thanks for the info, but the `ddfi2` code has a little messy, I will try to learn how to rewrite it, thanks~
