### ISSUE TITLE
How to Implement like Spatial TTA for rife-v4.x for VapourSynth?

### ISSUE THREAD

**Issue by Noir16** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#30]
According to the #6, It seems that VapourSynth alone can Implement like Spatial TTA even if the model does not support TTA, what parameters and related plugins should I use?
The newer models are more algorithmically advanced and I'd like to use them, but I can't use Spatial TTA and am looking for a way to reimplement them with VapourSynth.

**Comment by TNTwise** [comment]
I reconverted all the models and added tta here: https://github.com/TNTwise/rife-ncnn-vulkan/tree/master/models

**Comment by Noir16** [comment]
@TNTwise Thanks.

**Comment by styler00dollar** [comment]
I think @TNTwise got confused, since spacial tta is usually done outside of models. Spacial tta means to flip the input clip into various directions, use model, flip them back and merge the result into one clip. That can be done directly in vapoursynth and does not require modifications of the plugin or models.

**Comment by hooke007** [comment]
Yes, ensemble should be temporal-tta instead.
