### ISSUE TITLE
Document parameters

### ISSUE THREAD

**Issue by spaceman7777** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#43]
Hi, I've read through all of the code, and can't seem to find an explanation of what this filter's "tta", "uhd", or "ensemble" parameters mean, besides "uhd" meaning "uhd mode", and "tta" meaning "tta(time-test augmentation) mode".

Could you write down a bit more on what you mean by those terms? What effect do they have? When should, or shouldn't they be used?

Thank you

**Comment by mn7216** [comment]
https://github.com/hzwer/Practical-RIFE

Explained on the RIFE repo

**Comment by styler00dollar** [comment]
param | description
---------- | ----------------
(spacial) tta | Inputs two images where one is flipped and the output of the multiple inputs are merged into one
ensemble (aka temporal tta) | Unlike tta, it also merges the flow within the model and not only the outputs
uhd | scale=0.5 is used instead of 1, to have less flow resolution with `scale_list = [8/scale, 4/scale, 2/scale, 1/scale]`
